### ISSUE TITLE
sub schemas references not supported in Responses

### ISSUE THREAD

**Issue by mehdijouan** [phoenixnap/springmvc-raml-plugin#115] opened 2017-01-23 11:02 UTC
Hello,

I have two schemas:
* sample_unit.json
* sub_sample_unit.json

The `sample_unit.json` has a reference to `sub_sample_unit.json` like following :
```
...
    "subUnit":{
      "$ref":"sub_sample_unit.json"
    }
...
```
This referencing is supported by jsonschema2pojo (I tried it) but it fails when using the spring mvc plugin code generation.
```
Caused by: java.lang.IllegalArgumentException: URI is not absolute
	at java.net.URI.toURL(URI.java:1088)
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:67)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:48)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:116)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:59)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:75)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:43)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:64)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:32)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:115)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:66)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:90)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:40)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:134)
	at com.phoenixnap.oss.ramlapisync.naming.SchemaHelper.buildBodyJCodeModel(SchemaHelper.java:597)
	at com.phoenixnap.oss.ramlapisync.naming.SchemaHelper.mapSchemaToPojo(SchemaHelper.java:519)
	at com.phoenixnap.oss.ramlapisync.data.ApiActionMetadata.collectBodyParams(ApiActionMetadata.java:146)
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.lambda$entryConsumer$101(Collections.java:1575)
	at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:663)
	at java.util.Collections$UnmodifiableMap$UnmodifiableEntrySet.forEach(Collections.java:1580)
	at com.phoenixnap.oss.ramlapisync.data.ApiActionMetadata.parseRequest(ApiActionMetadata.java:131)
	at com.phoenixnap.oss.ramlapisync.data.ApiActionMetadata.<init>(ApiActionMetadata.java:70)
	at com.phoenixnap.oss.ramlapisync.data.ApiResourceMetadata.addApiCall(ApiResourceMetadata.java:60)
	at com.phoenixnap.oss.ramlapisync.generation.RamlParser.checkResource(RamlParser.java:177)
	at com.phoenixnap.oss.ramlapisync.generation.RamlParser.extractControllers(RamlParser.java:102)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.generateEndpoints(SpringMvcEndpointGeneratorMojo.java:213)
	at com.phoenixnap.oss.ramlapisync.plugin.SpringMvcEndpointGeneratorMojo.execute(SpringMvcEndpointGeneratorMojo.java:416)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 27 more
```
While running the plugin in debug,  I saw that the SchemaHelper has a schemaLocaltion equals to `classpath:/` but as `sub_sample_unit.json` is not in the classpath, it does not work. if base schema location path was provided, jsonschema2pojo would have handled it correctly.

You can have a look at [this sample project](https://github.com/mehdijouan/springmvc-raml-plugin-sample) to see an example with the issue

**Comment by kurtpa** [comment] 2017-02-02 10:05
Hiya, sorry for the late reply,

The <schemaLocation>{path.to.schema.directory||schema.absolute.url}</schemaLocation> configuration in the pom should allow you to define a folder in your project, and all schemas there will be added to the classpath.

Try it out and see if this works for you :)

**Comment by kurtpa** [comment] 2017-03-02 06:02
Any update on whether this configuration worked?

**Comment by AdminAffe** [comment] 2017-03-14 08:47
I stumbled upon the same problem and I can confirm that this solution works quite well. 
I took it to the next level, though. My folder structure looks like this:
- src/main/resources/raml
  - schemas
    - adresse-request.json
    - adresse-response.json
    - adresse-revision-response.json
    - error-response.json
  - api.raml
  - schemas.raml
  - traits.raml

Every JSON contains the definition for its corresponding object. The schemas.raml merges all objects so I can include them into the api.raml. In the configuration the schemaLocation has to point to the root folder where the schemas.raml is contained: `<schemaLocation>/src/main/resources/raml</schemaLocation>`

Example: I am using envers in my project, so I want to return a list of revisions containing the actual object.

adresse-revision-response.json
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "revId": {
        "type": "integer"
      },
    "revDate": {
        "type": "date"
      },
    "revMandant": {
        "type": "string"
      },
    "revBenutzername": {
        "type": "string"
      },
    "adresseResponse": {
        "$ref": "adresse-response.json"
      }
  }
}
```
schemas.raml
```
ErrorResponse: |
  {
    "$ref": "schemas/error-response.json"
  }
AdresseRequest: |
  {
    "$ref": "schemas/adresse-request.json"
  }
AdresseResponse: |
  {
    "$ref": "schemas/adresse-response.json"
  }
AdresseRevisionResponse: |
  {
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "$ref": "schemas/adresse-revision-response.json"
      }
  }
```
api.raml
```
#%RAML 0.8
title: AdressDataService
version: 1.0.0
documentation:
  - title: Verwaltung von Adress-Daten
    content: |
      Dieser Service ist für die Verwaltung von Adress-Daten zuständig.

schemas:
  - !include schemas.raml
traits:
  - !include traits.raml

[...]
```

**Comment by kurtpa** [comment] 2017-03-14 08:49
cool! thanks for the update and advice. 

I'm going to close this issue then - i also need to group up all these good pieces of config/advice into our wiki *adds to todo :)*

**Closed by kurtpa** 2017-03-14 08:49 UTC
