### ISSUE TITLE
[RAML To CODE] Issue with array in request/response

### ISSUE THREAD

**Issue by YannickG1** [phoenixnap/springmvc-raml-plugin#134] opened 2017-03-19 13:04 UTC
Hi,

First of all, thumbs up for this implementation, i like it very much. Although I'm running into a basic issue here so I guess I'm doing something wrong on my side. Here is my RAML:

```
#%RAML 0.8
title: AccountService
version: v1
baseUri: http://localhost:8080
schemas:
  - accounts: !include schemas/accounts.schema.json
  - account: !include schemas/account.schema.json
  - errorResource: !include schemas/errorResource.schema.json

/accounts:
  get:
    description: Get list of accounts
    responses:
      200:
        description: Successful request
        body:
          application/json:
            schema: accounts
            example: !include examples/accounts.example.json
      404:
        description: Nothing found for your request
        body:
          application/json:
           schema: errorResource
      500:
        description: Internal server error
        body:
          application/json:
           schema: errorResource
  post:
    description: Create new accountS
    body:
      application/json:
       schema: accounts
       example: !include examples/accounts.example.json
    responses:
      201:
        description: Object created succesfully.
      400:
        description: Bad request. The provided input does not comply to the contract.
        body:
          application/json:
           schema: errorResource
      500:
        description: Internal server error
        body:
          application/json:
           schema: errorResource
  /{accountId}:
      displayName: Get Account Details
      get:
        description: Retrieve account details
        responses:
          200:
            description: Successful request
            body:
              application/json:
                schema: account
                example: !include examples/account.example.json
          404:
            description: Nothing found for your request
            body:
              application/json:
               schema: errorResource
          500:
            description: Internal server error
            body:
              application/json:
               schema: errorResource
      delete:
        description: Delete account
        responses:
          204:
            description: Account deleted
          404:
            description: Nothing found for your request
            body:
              application/json:
               schema: errorResource
          500:
            description: Internal server error
            body:
              application/json:
               schema: errorResource
```

Here is accounts.json (No $ref used to account.json because I've had enough issues with that in the past so I'm using it in a basic copy-paste way this time.

```
{
	"$schema": "http://json-schema.org/draft-04/schema",	
	"id": "accounts",
	"definitions": {
		"moneyAmount": {
			"type": "object",
			"properties": {
				"amount": {
					"type": "number"
				},

				"currency": {
					"type": "string"
				}
			}
		}
	},
	"type": "array",
	"items": {
		"type": "object",
		"properties": {
			"label": {
				"type": "string"
			},

			"type": {
				"type": "string",
				"enum": ["checkings", "savings"]
			},

			"owners": {
				"type": "array",
				"items": {
					"type": "string"
				}
			},

			"iban": {
				"type": "string",
				"pattern": "[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[0-9]{7}([a-zA-Z0-9]?){0,16}"
			},

			"moneyAmount": {
				"$ref": "#/definitions/moneyAmount"
			}
		}					
	}
}
```

And here is account.json, which is the same as accounts, just without the array wrapper around it:
```
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"id": "account",
	"definitions": {
		"moneyAmount": {
			"type": "object",
			"properties": {
				"amount": {
					"type": "number"
				},

				"currency": {
					"type": "string"
				}
			}
		}
	},	
	"type": "object",	
	"properties": {
		"label": {
			"type": "string"
		},

		"type": {
			"type": "string",
			"enum": ["checkings", "savings"]
		},

		"owners": {
			"type": "array",
			"items": {
				"type": "string"
			}
		},

		"iban": {
			"type": "string",
			"pattern": "[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{4}[0-9]{7}([a-zA-Z0-9]?){0,16}"
		},

		"moneyAmount": {
			"$ref": "#/definitions/moneyAmount"
		}			
	}	
}

```
Now for some reason, this is the AccountController he is generating:

```
package be.ae.aeatuniversity;

import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;


/**
 * No description
 * (Generated with springmvc-raml-parser v.0.9.1)
 * 
 */
@RestController
@RequestMapping("/api/accounts")
public class AccountController {


    /**
     * Get list of accounts
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.GET)
    public be.ae.aeatuniversity.model.Account getAccounts() {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Create a new account
     * 
     */
    @RequestMapping(value = "", method = RequestMethod.POST)
    public ResponseEntity<?> createAccount(
        @Valid
        @RequestBody
        be.ae.aeatuniversity.model.Account account) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Retrieve account details
     * 
     */
    @RequestMapping(value = "/{accountId}", method = RequestMethod.GET)
    public be.ae.aeatuniversity.model.Account getAccountById(
        @PathVariable
        String accountId) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

    /**
     * Delete account
     * 
     */
    @RequestMapping(value = "/{accountId}", method = RequestMethod.DELETE)
    public ResponseEntity<?> deleteAccountById(
        @PathVariable
        String accountId) {
        return null; //TODO Autogenerated Method Stub. Implement me please.
    }

}
```

As you can see, all 4 operations have the type "Account", while 2 of them should have the type "List\<Account\>". What am I doing wrong ? Thanks in advance!

**Comment by kurtpa** [comment] 2017-03-20 06:06
Hi Yannick

This has been the prime motivator for us to move to RAML 1.0 - the types are much easier to write and parse then are the JSON Schemas. Having said that, this *should* work :) I'll be taking a look at your raml and trying to figure out why this is happening.

**Comment by kurtpa** [comment] 2017-03-20 06:08
The issue is in ApiBodyMetadata.java:59 - the issue is that the definitions block is listed before the "type" and as such the parser is mistakenly using the type in the "definitions" block. I'll fix the code to ignore this, but in the meantime moving "type":"array" right after id will fix it.

**Comment by kurtpa** [comment] 2017-03-20 06:19
Closing issue, we can reopen if there are any issues left. The codefix for this will be out with 0.10.2

**Comment by YannickG1** [comment] 2017-03-23 16:41
Hi,

I tried your new version and this fixes the issue with the GET call, put the POST call is still only accepting 1 account and not a list of accounts :)

Best regards,
Yannick

**Comment by kurtpa** [comment] 2017-03-28 13:19
I looked at the code, and it was an intentional decision at the time to not support List<x> in the parameters. The main reason for this is that (at the time) java generics would cause this to be lost

(http://stackoverflow.com/questions/4441557/rest-with-spring-and-jackson-full-data-binding)

I'm wondering if this should still hold or whether we should allow List<XXX> in parameters annotated with @RequestBody

**Closed** 2017-03-29 14:10 UTC
