### ISSUE TITLE
RAML 1.0 not picking up dateType from generationConfig 

### ISSUE THREAD

**Issue by youac** [phoenixnap/springmvc-raml-plugin#240] opened 2018-03-16 11:11 UTC
When setting dateType in generationConfig to use LocalDate, code is being generated with a java.util.Date

generationConfig: 
```
<generationConfig>
     <dateType>org.joda.time.LocalDate</dateType>
</generationConfig>
```

In the RAML: 
`dateOfBirth: 
      type: date-only`

Code generated: 
```private Date dateOfBirth; ```

Expected code: 
`private LocalDate dateOfBirth; `

Could you please advise

**Comment by stojsavljevic** [comment] 2018-05-14 08:35
Basically, #253 is duplicate of this one.
Resolved with 1f90a82

**Closed by stojsavljevic** 2018-05-14 08:35 UTC
Labels: question
